CREATE TABLE HISTRECORDS(
    DAY INTEGER,
    MONTH INTEGER,
    YEAR INTEGER,
    HOUR INTEGER,
    MINUTE INTEGER,
    TEMP REAL,
    HUM REAL
);

CREATE TABLE EVENTS(
    ID INTEGER,
    START_TEMP REAL,
    MONDAY INTEGER,
    TUESDAY INTEGER,
    WEDNESDAY INTEGER,
    THURSDAY INTEGER,
    FRIDAY INTEGER,
    SATURDAY INTEGER,
    SUNDAY INTEGER,
    START_HOUR INTEGER,
    START_MIN INTEGER,
    END_HOUR INTEGER,
    END_MIN INTEGER,
    ACTIVE INTEGER
);
