CREATE TABLE HISTRECORDS(
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    HOUR INTEGER,
    MINUTE INTEGER,
    TEMP REAL,
    HUM REAL
);

CREATE TABLE EVENTS(
    START_TEMP REAL,
    PERIODIC TEXT,
    BY_TIME INTEGER,
    START_HOUR INTEGER,
    START_MIN INTEGER,
    END_HOUR INTEGER,
    END_MIN INTEGER,
    ACTIVE INTEGER
);

CREATE TABLE USAGE(
    YEAR INTEGER,
    MONTH INTEGER,
    DAY INTEGER,
    START_HOUR INTEGER,
    START_MIN INTEGER,
    START_SEC INTEGER,
    END_HOUR INTEGER,
    END_MIN INTEGER,
    END_SEC INTEGER
);
